Repository soniyash9000/Data-Structure-and-Algotihms, pull requests merged in 2022-10, with the labels that each got.

#22 Added file of Circular-Queue using Linkedlist .
  Circular-Queue-Linked-List.c
Labels: hacktoberfest, hacktoberfest-accepted

#23 added dda line drawing algorithm
  dda.cpp
Labels: hacktoberfest, hacktoberfest-accept

#24 implementing linked list concepts using class
  linked_list_using_class.cpp
Labels: hacktoberfest-accept

#25 singly Linked List
  singlyLinkedList.cpp
Labels: hacktoberfest-accept

#28 Prime number
  prime_number.cpp
Labels: hacktoberfest-accept

#30 Added bresenham code
  bresenham_algo.cpp
Labels: hacktoberfest-accept

#31 Update dda.cpp
  dda.cpp
Labels: hacktoberfest-accept

#32 Added Number of Steps to Reduce a Number to Zero
  Number of Steps to Reduce_a_Number_to_Zero.cpp
Labels: hacktoberfest-accept

#34 updated file
  multiply_polynomial_linked_list.c
Labels: hacktoberfest-accept

#33 Added_Check_pallindrome
  pallindrome.c
Labels: hacktoberfest-accept

#35 Matrix-Chain Multiplication DP
  MatrixChainMultiplication.java
Labels: hacktoberfest-accept

#36 Create singlyLinkedList.c
  singlyLinkedList.c
Labels: hacktoberfest-accept

#37 Diagonal Matrix.c
  Diagonal Matrix.c
Labels: hacktoberfest-accept

#38 Added a new code of DSA
  Doubly-linked-list.c
Labels: hacktoberfest-accept
